spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banco_sge
    username: postgres
    password: goku_agiota_123

  jackson:
    fail-on-unknown-properties: false

  jpa:
    hibernate:
#      dialect: org.hibernate.dialect.PostgreSQLDialect
      dll-auto: update

  liquibase:
    change-log: classpath:/db/changelog-master.xml
#    drop-first: true

security:
  basic:
    enabled: false

management:
  security:
    enabled: false